# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        MainWindow.setMinimumSize(QtCore.QSize(480, 320))
        MainWindow.setMaximumSize(QtCore.QSize(480, 320))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        MainWindow.setPalette(palette)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        MainWindow.setStyleSheet("* {\n"
"    /*background-color: black;\n"
"    color: lightblue;*/\n"
"}\n"
"")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.stkMain = QtWidgets.QStackedWidget(self.centralWidget)
        self.stkMain.setGeometry(QtCore.QRect(0, 0, 481, 321))
        self.stkMain.setMinimumSize(QtCore.QSize(481, 0))
        self.stkMain.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.stkMain.setObjectName("stkMain")
        self.stkPgCur = QtWidgets.QWidget()
        self.stkPgCur.setObjectName("stkPgCur")
        self.lblCurDataBig = QtWidgets.QLabel(self.stkPgCur)
        self.lblCurDataBig.setGeometry(QtCore.QRect(10, 39, 300, 121))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(45)
        self.lblCurDataBig.setFont(font)
        self.lblCurDataBig.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurDataBig.setMouseTracking(False)
        self.lblCurDataBig.setAutoFillBackground(False)
        self.lblCurDataBig.setStyleSheet("")
        self.lblCurDataBig.setScaledContents(True)
        self.lblCurDataBig.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCurDataBig.setObjectName("lblCurDataBig")
        self.frmForWthr = QtWidgets.QFrame(self.stkPgCur)
        self.frmForWthr.setGeometry(QtCore.QRect(245, 170, 225, 140))
        self.frmForWthr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmForWthr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmForWthr.setObjectName("frmForWthr")
        self.cbxForDataStat = QtWidgets.QComboBox(self.frmForWthr)
        self.cbxForDataStat.setGeometry(QtCore.QRect(10, 30, 205, 22))
        self.cbxForDataStat.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.cbxForDataStat.setCurrentText("")
        self.cbxForDataStat.setObjectName("cbxForDataStat")
        self.label_8 = QtWidgets.QLabel(self.frmForWthr)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_8.setObjectName("label_8")
        self.lblForNm1 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForNm1.setGeometry(QtCore.QRect(10, 60, 125, 16))
        self.lblForNm1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForNm1.setFont(font)
        self.lblForNm1.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForNm1.setObjectName("lblForNm1")
        self.lblForNm2 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForNm2.setGeometry(QtCore.QRect(10, 80, 125, 16))
        self.lblForNm2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForNm2.setFont(font)
        self.lblForNm2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForNm2.setObjectName("lblForNm2")
        self.lblForNm3 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForNm3.setGeometry(QtCore.QRect(10, 100, 125, 16))
        self.lblForNm3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForNm3.setFont(font)
        self.lblForNm3.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForNm3.setObjectName("lblForNm3")
        self.lblForNm4 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForNm4.setGeometry(QtCore.QRect(10, 120, 125, 16))
        self.lblForNm4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForNm4.setFont(font)
        self.lblForNm4.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForNm4.setObjectName("lblForNm4")
        self.lblForUnit1 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForUnit1.setGeometry(QtCore.QRect(180, 60, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForUnit1.setFont(font)
        self.lblForUnit1.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForUnit1.setObjectName("lblForUnit1")
        self.lblForUnit3 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForUnit3.setGeometry(QtCore.QRect(180, 100, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForUnit3.setFont(font)
        self.lblForUnit3.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForUnit3.setObjectName("lblForUnit3")
        self.lblForData3 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForData3.setGeometry(QtCore.QRect(135, 100, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForData3.setFont(font)
        self.lblForData3.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForData3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblForData3.setObjectName("lblForData3")
        self.lblForUnit4 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForUnit4.setGeometry(QtCore.QRect(180, 120, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForUnit4.setFont(font)
        self.lblForUnit4.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForUnit4.setObjectName("lblForUnit4")
        self.lblForUnit2 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForUnit2.setGeometry(QtCore.QRect(180, 80, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForUnit2.setFont(font)
        self.lblForUnit2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForUnit2.setObjectName("lblForUnit2")
        self.lblForData1 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForData1.setGeometry(QtCore.QRect(135, 60, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForData1.setFont(font)
        self.lblForData1.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForData1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblForData1.setObjectName("lblForData1")
        self.lblForData4 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForData4.setGeometry(QtCore.QRect(135, 120, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForData4.setFont(font)
        self.lblForData4.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForData4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblForData4.setObjectName("lblForData4")
        self.lblForData2 = QtWidgets.QLabel(self.frmForWthr)
        self.lblForData2.setGeometry(QtCore.QRect(135, 80, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblForData2.setFont(font)
        self.lblForData2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblForData2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblForData2.setObjectName("lblForData2")
        self.frmCurWthr = QtWidgets.QFrame(self.stkPgCur)
        self.frmCurWthr.setGeometry(QtCore.QRect(10, 170, 225, 140))
        self.frmCurWthr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmCurWthr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmCurWthr.setObjectName("frmCurWthr")
        self.cbxCurDataStat = QtWidgets.QComboBox(self.frmCurWthr)
        self.cbxCurDataStat.setGeometry(QtCore.QRect(10, 30, 205, 22))
        self.cbxCurDataStat.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.cbxCurDataStat.setCurrentText("")
        self.cbxCurDataStat.setObjectName("cbxCurDataStat")
        self.lblCurUnit1 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurUnit1.setGeometry(QtCore.QRect(180, 60, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurUnit1.setFont(font)
        self.lblCurUnit1.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurUnit1.setObjectName("lblCurUnit1")
        self.lblCurNm1 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurNm1.setGeometry(QtCore.QRect(10, 60, 125, 16))
        self.lblCurNm1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurNm1.setFont(font)
        self.lblCurNm1.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurNm1.setObjectName("lblCurNm1")
        self.lblCurData1 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurData1.setGeometry(QtCore.QRect(135, 60, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurData1.setFont(font)
        self.lblCurData1.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurData1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCurData1.setObjectName("lblCurData1")
        self.lblCurNm2 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurNm2.setGeometry(QtCore.QRect(10, 80, 125, 16))
        self.lblCurNm2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurNm2.setFont(font)
        self.lblCurNm2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurNm2.setObjectName("lblCurNm2")
        self.lblCurNm3 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurNm3.setGeometry(QtCore.QRect(10, 100, 125, 16))
        self.lblCurNm3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurNm3.setFont(font)
        self.lblCurNm3.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurNm3.setObjectName("lblCurNm3")
        self.lblCurNm4 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurNm4.setGeometry(QtCore.QRect(10, 120, 125, 16))
        self.lblCurNm4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurNm4.setFont(font)
        self.lblCurNm4.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurNm4.setObjectName("lblCurNm4")
        self.lblCurUnit2 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurUnit2.setGeometry(QtCore.QRect(180, 80, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurUnit2.setFont(font)
        self.lblCurUnit2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurUnit2.setObjectName("lblCurUnit2")
        self.lblCurData2 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurData2.setGeometry(QtCore.QRect(135, 80, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurData2.setFont(font)
        self.lblCurData2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurData2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCurData2.setObjectName("lblCurData2")
        self.lblCurUnit3 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurUnit3.setGeometry(QtCore.QRect(180, 100, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurUnit3.setFont(font)
        self.lblCurUnit3.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurUnit3.setObjectName("lblCurUnit3")
        self.lblCurData3 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurData3.setGeometry(QtCore.QRect(135, 100, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurData3.setFont(font)
        self.lblCurData3.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurData3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCurData3.setObjectName("lblCurData3")
        self.lblCurUnit4 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurUnit4.setGeometry(QtCore.QRect(180, 120, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurUnit4.setFont(font)
        self.lblCurUnit4.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurUnit4.setObjectName("lblCurUnit4")
        self.lblCurData4 = QtWidgets.QLabel(self.frmCurWthr)
        self.lblCurData4.setGeometry(QtCore.QRect(135, 120, 40, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurData4.setFont(font)
        self.lblCurData4.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurData4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCurData4.setObjectName("lblCurData4")
        self.label_9 = QtWidgets.QLabel(self.frmCurWthr)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_9.setObjectName("label_9")
        self.lblWthrIcon = QtWidgets.QLabel(self.stkPgCur)
        self.lblWthrIcon.setGeometry(QtCore.QRect(320, 10, 150, 150))
        self.lblWthrIcon.setText("")
        self.lblWthrIcon.setObjectName("lblWthrIcon")
        self.lblCurNmBig = QtWidgets.QLabel(self.stkPgCur)
        self.lblCurNmBig.setGeometry(QtCore.QRect(10, 10, 125, 16))
        self.lblCurNmBig.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.lblCurNmBig.setFont(font)
        self.lblCurNmBig.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lblCurNmBig.setTextFormat(QtCore.Qt.AutoText)
        self.lblCurNmBig.setObjectName("lblCurNmBig")
        self.frmCurWthr.raise_()
        self.frmForWthr.raise_()
        self.lblCurDataBig.raise_()
        self.lblWthrIcon.raise_()
        self.lblCurNmBig.raise_()
        self.stkMain.addWidget(self.stkPgCur)
        self.stkPgFor = QtWidgets.QWidget()
        self.stkPgFor.setObjectName("stkPgFor")
        self.label = QtWidgets.QLabel(self.stkPgFor)
        self.label.setGeometry(QtCore.QRect(130, 80, 59, 14))
        self.label.setObjectName("label")
        self.stkMain.addWidget(self.stkPgFor)
        self.stkPgRdr = QtWidgets.QWidget()
        self.stkPgRdr.setObjectName("stkPgRdr")
        self.label_2 = QtWidgets.QLabel(self.stkPgRdr)
        self.label_2.setGeometry(QtCore.QRect(380, 220, 59, 14))
        self.label_2.setObjectName("label_2")
        self.lblRdrImg = QtWidgets.QLabel(self.stkPgRdr)
        self.lblRdrImg.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.lblRdrImg.setText("")
        self.lblRdrImg.setObjectName("lblRdrImg")
        self.lblRdrImg.raise_()
        self.label_2.raise_()
        self.stkMain.addWidget(self.stkPgRdr)
        self.stkPgGraph = QtWidgets.QWidget()
        self.stkPgGraph.setObjectName("stkPgGraph")
        self.label_4 = QtWidgets.QLabel(self.stkPgGraph)
        self.label_4.setGeometry(QtCore.QRect(140, 160, 59, 14))
        self.label_4.setObjectName("label_4")
        self.stkMain.addWidget(self.stkPgGraph)
        self.stkPgStg = QtWidgets.QWidget()
        self.stkPgStg.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.stkPgStg.setObjectName("stkPgStg")
        self.label_3 = QtWidgets.QLabel(self.stkPgStg)
        self.label_3.setGeometry(QtCore.QRect(110, 200, 59, 14))
        self.label_3.setObjectName("label_3")
        self.stkMain.addWidget(self.stkPgStg)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.stkMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblCurDataBig.setText(_translate("MainWindow", "NA"))
        self.label_8.setText(_translate("MainWindow", "Today\'s Forecast"))
        self.lblForNm1.setText(_translate("MainWindow", "High Temperature"))
        self.lblForNm2.setText(_translate("MainWindow", "Low Temperature"))
        self.lblForNm3.setText(_translate("MainWindow", "Average Humidity"))
        self.lblForNm4.setText(_translate("MainWindow", "Avg. Relative Humdity"))
        self.lblForUnit1.setText(_translate("MainWindow", "°F"))
        self.lblForUnit3.setText(_translate("MainWindow", "%"))
        self.lblForData3.setText(_translate("MainWindow", "NA"))
        self.lblForUnit4.setText(_translate("MainWindow", "mph"))
        self.lblForUnit2.setText(_translate("MainWindow", "°F"))
        self.lblForData1.setText(_translate("MainWindow", "NA"))
        self.lblForData4.setText(_translate("MainWindow", "NA"))
        self.lblForData2.setText(_translate("MainWindow", "NA"))
        self.lblCurUnit1.setText(_translate("MainWindow", "in"))
        self.lblCurNm1.setText(_translate("MainWindow", "Pressure"))
        self.lblCurData1.setText(_translate("MainWindow", "NA"))
        self.lblCurNm2.setText(_translate("MainWindow", "Relative Humidity"))
        self.lblCurNm3.setText(_translate("MainWindow", "Wind"))
        self.lblCurNm4.setText(_translate("MainWindow", "Feels Like"))
        self.lblCurUnit2.setText(_translate("MainWindow", "%"))
        self.lblCurData2.setText(_translate("MainWindow", "NA"))
        self.lblCurUnit3.setText(_translate("MainWindow", "mph"))
        self.lblCurData3.setText(_translate("MainWindow", "NA"))
        self.lblCurUnit4.setText(_translate("MainWindow", "°F"))
        self.lblCurData4.setText(_translate("MainWindow", "NA"))
        self.label_9.setText(_translate("MainWindow", "Current Weather"))
        self.lblCurNmBig.setText(_translate("MainWindow", "Temperature"))
        self.label.setText(_translate("MainWindow", "Forecast"))
        self.label_2.setText(_translate("MainWindow", "Radar"))
        self.label_4.setText(_translate("MainWindow", "Graph"))
        self.label_3.setText(_translate("MainWindow", "Settings"))

